In [ ]:
# sort :-

# 1D :
import numpy as np
arr = np.array([10,40,30,60,90,7,5])
print(arr)
arr_s = np.sort(arr)                      # accending order
print(arr_s)
arr_ss = np.sort(arr)[::-1]               # decending order
print(arr_ss)


# 2d :
# axis = 0 ->coloums
# axis = 1 ->rows
arr1 = np.array([[10,40,30,60,90,7,5],[1,2,3,4,5,6,7]])
print("\n",arr1)
arr1_s = np.sort(arr1)          # by default row wise
print("\n",arr1_s)

arr1_ss = np.sort(arr1,axis = 0)
print("\n",arr1_ss)

arr1_sss = np.sort(arr1)[::-1]
print("\n",arr1_sss)



[10 40 30 60 90  7  5]
[ 5  7 10 30 40 60 90]
[90 60 40 30 10  7  5]

 [[10 40 30 60 90  7  5]
 [ 1  2  3  4  5  6  7]]

 [[ 5  7 10 30 40 60 90]
 [ 1  2  3  4  5  6  7]]

 [[ 1  2  3  4  5  6  5]
 [10 40 30 60 90  7  7]]

 [[ 1  2  3  4  5  6  7]
 [ 5  7 10 30 40 60 90]]


In [ ]:
# Filter :
import numpy as np
arr = np.array([10,40,30,65,90,7,5])
print(arr)
arr_f = arr[arr<40]
print(arr_f)

arr_ff = arr[arr%2==0]
print(arr_ff)


[10 40 30 65 90  7  5]
[10 30  7  5]
[10 40 30 90]


In [ ]:
# Fancy indexing :
import numpy as np
arr = np.array([23,45,21,10,40,34,90,50])
print(arr)
arr_l = arr[[0,2]]
print(arr_l)


# 2D :
arr1 = np.arange(12).reshape(3,4)
print(arr1)
arr_ll = arr1[[1,2],[0,2]]
print(arr_ll)


[23 45 21 10 40 34 90 50]
[23 21]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 4 10]


In [ ]:
# where :
import numpy as np
arr = np.array([10,40,30,60,90,7,5])
print(arr)
arr_w = np.where(arr<4)
print(arr_w)
arr_ww = np.where(arr >40 , arr*2 ,arr -arr)
print(arr_ww)


[10 40 30 60 90  7  5]
(array([], dtype=int64),)
[  0   0   0 120 180   0   0]


In [ ]:
# concatenate :-
# 1D :
import numpy as np
arr1 = np.array([10,40,30,60,90,7,5])
arr2 = np.array([1,2,3,4,5,6,7])
print(arr1)
print(arr2)
arr_c = np.concatenate((arr1,arr2))      # tuple ki form mai data dena hoga
print(arr_c)

# 2D :
arr = np.ones((2,3))
arrl =  np.zeros((2,3))
arr_cc = np.concatenate((arr ,arrl) , axis=0)
print("\n",arr_cc)



[10 40 30 60 90  7  5]
[1 2 3 4 5 6 7]
[10 40 30 60 90  7  5  1  2  3  4  5  6  7]

 [[1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
# flat() :-
import numpy as np
a = np.arange(12).reshape(3,4)
print(a)
a1 = a.flat[4]
print(a1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
4


In [7]:
# ndarray.T :-
import numpy as np
b = np.arange(12).reshape(3,4)
print(b)
b1 = b.T
print("\n",b1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [14]:
# rollaxis() :-
import numpy as np
b = np.arange(12).reshape(3,4)
print(b)
r = np.rollaxis(b,1)
print(r)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [19]:
#swapaxes(arr,axis1,axis2) :-
import numpy as np
a = np.arange(12).reshape(3,4)
print(a)
b = np.swapaxes(a,1,1)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [21]:
# stack(arrays,axis) :-
import numpy as np
a = np.array([[1,2],[3,4]])
print("first array :" ,a)
b = np.array([[5,6],[7,8]])
print("second array :",b)
print("\n Stack the two array along axis 0 :")
print(np.stack((a,b),0))
print("\n Stack the two array along axis 1 :")
print(np.stack((a,b),1))


first array : [[1 2]
 [3 4]]
second array : [[5 6]
 [7 8]]

 Stack the two array along axis 0 :
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

 Stack the two array along axis 1 :
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [22]:
# hstack  :-  in column wise
import numpy as np
a = np.array([[1,2],[3,4]])
print("first array :" ,a)
b = np.array([[5,6],[7,8]])
print("second array :",b)
c = np.hstack((a,b))
print("Horizontal stacking :")
print(c)


first array : [[1 2]
 [3 4]]
second array : [[5 6]
 [7 8]]
Horizontal stacking :
[[1 2 5 6]
 [3 4 7 8]]


In [23]:
# vstack :- in row wise
import numpy as np
a = np.array([[1,2],[3,4]])
print("first array :" ,a)
b = np.array([[5,6],[7,8]])
print("second array :",b)
c = np.vstack((a,b))
print("Vertical stacking :")
print(c)


first array : [[1 2]
 [3 4]]
second array : [[5 6]
 [7 8]]
Vertical stacking :
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
