In [ ]:
# Numpy :-
# Numpy VS List :
# learn how to use in Visual studio code :
#import numpy as np
# from numpy import arange
# from numpy import *
import numpy
n = numpy.arange(11)
print(type(n))
print(n)



<class 'numpy.ndarray'>
[ 0  1  2  3  4  5  6  7  8  9 10]


In [ ]:
# example :
n = numpy.arange(12)
d = n.reshape(3,4)              # 3 -> Rows and 4 -> colunms
print(type(d))
print(d)

# another way :
n = numpy.arange(12).reshape(4,3)
print(n)

# 3d :
h = numpy.arange(24).reshape(2,3,4)
print(h)

<class 'numpy.ndarray'>
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
import numpy
n = numpy.arange(12).reshape(4,3)
print(n)
print(n[0:4,2:4])          # one way
print(n[0:4:,2])           # second way -> by jump
print(n[1:3,1:2])
print(n[1:3,1])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 2]
 [ 5]
 [ 8]
 [11]]
[ 2  5  8 11]
[[4]
 [7]]
[4 7]


In [2]:
# eye() method  -> used to create 2D array  -> diagonal mai 1's and left over mai 0's
import numpy as np
x1 = np.eye(5)
print(x1)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [3]:
import numpy as np
data = [1,2,3,4,5]
a = np.array(data)
for i in a:
  print(i)

1
2
3
4
5


In [5]:
import numpy as np
data1 = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]
b = np.array(data1)
print(b)
for i in b:
  for j in i:
    print(j)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
