In [ ]:
# Numpy :-
# Numpy VS List :
# learn how to use in Visual studio code :
#import numpy as np
# from numpy import arange
# from numpy import *
import numpy
n = numpy.arange(11)
print(type(n))
print(n)



<class 'numpy.ndarray'>
[ 0  1  2  3  4  5  6  7  8  9 10]


In [ ]:
# example :
n = numpy.arange(12)
d = n.reshape(3,4)              # 3 -> Rows and 4 -> colunms
print(type(d))
print(d)

# another way :
n = numpy.arange(12).reshape(4,3)
print(n)

# 3d :
h = numpy.arange(24).reshape(2,3,4)
print(h)

<class 'numpy.ndarray'>
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
import numpy
n = numpy.arange(12).reshape(4,3)
print(n)
print(n[0:4,2:4])          # one way
print(n[0:4:,2])           # second way -> by jump
print(n[1:3,1:2])
print(n[1:3,1])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 2]
 [ 5]
 [ 8]
 [11]]
[ 2  5  8 11]
[[4]
 [7]]
[4 7]


In [ ]:
# eye() method  -> used to create 2D array  -> diagonal mai 1's and left over mai 0's
import numpy as np
x1 = np.eye(5)
print(x1)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
import numpy as np
data = [1,2,3,4,5]
a = np.array(data)
for i in a:
  print(i)

1
2
3
4
5


In [ ]:
import numpy as np
data1 = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]
b = np.array(data1)
print(b)
for i in b:
  for j in i:
    print(j)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [9]:
import numpy as np                             # same as * (multiple) , ** (power) , / (divide) ,% (mod)
data = [1,2,3,4,5]
data1 = [6,7,8,9,10]
x = np.array(data)
y = np.array(data1)
x1 = x + x
y1 = y-y
x2 = np.add(x,x)
y2 = np.subtract(y,y)
print(x1)
print(y1)
print(x2)
print(y2)


[ 2  4  6  8 10]
[0 0 0 0 0]
[ 2  4  6  8 10]
[0 0 0 0 0]


In [12]:
# mean and mediam
import numpy as np
a = np.array([1,2,3,4,5,6 ,7 ,10])
print(np.mean(a))
print(np.median(a))

4.75
4.5


In [17]:
# maximum and minimum :
import numpy as np
a = np.array([2,23,45,76,12,91,101,1100])
x1 = np.max(a)
x2 = np.min(a)
print(x1)
print(x2)
x3 = np.amax(a)
print(x3)

1100
2
1100


In [21]:
# percentile:
a = np.array([20,10,45,1,2,6])
x1 = np.percentile(a,50)
print(x1)

8.0


In [24]:
# <,> , == , != , <= ,>=
import numpy as np                                        # we are also use less(), less_equal() , greater() ,greater_equal() , equal(),not_equal()
x = np.array([1,2,4,6,8])
y = np.array([3,5,8,1,8])
result = x < y
print(result)
result1 = x > y
print(result1)
result2 = x == y
print(result2)
result3 = x != y
print(result3)

[ True  True  True False False]
[False False False  True False]
[False False False False  True]
[ True  True  True  True False]


In [31]:
# where command:
import numpy as np
a = np.array([23,45,67,89,91,90,20])
result = np.where( a > 60  )
print(result)

result2 = np.where(a % 2 == 0)
print(result2)

result3 = np.where(a > 60 , a*2 , a-2)       # a > 60 toh a * 2 , verna a -2 kar do
print(result3)

(array([2, 3, 4, 5]),)
(array([5, 6]),)
[ 21  43 134 178 182 180  18]
