In [2]:
# Numpy :-
# Numpy VS List :
# learn how to use in Visual studio code :
#import numpy as np
# from numpy import arange
# from numpy import *
import numpy
n = numpy.arange(11)
print(type(n))
print(n)



<class 'numpy.ndarray'>
[ 0  1  2  3  4  5  6  7  8  9 10]


In [7]:
# example :
n = numpy.arange(12)
d = n.reshape(3,4)              # 3 -> Rows and 4 -> colunms
print(type(d))
print(d)

# another way :
n = numpy.arange(12).reshape(4,3)
print(n)

# 3d :
h = numpy.arange(24).reshape(2,3,4)
print(h)

<class 'numpy.ndarray'>
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
