In [9]:
u = [2,3,4,5]
n = map(lambda x: x ** x,u)
print(list(n))

[4, 27, 256, 3125]


In [11]:
# numpy:-
import numpy as np
l = [1,2,3]
print(l)


#array id
arr = np.array(l)
print(arr)

[1, 2, 3]
[1 2 3]


In [23]:
import numpy as np
# 2d list
l = [[1,2,3],[4,5,6]]
print(l)
print(l[0])       # complete first row
print(l[0][0])    # first element of first row
print(l[0][1])    # second element of the first row
l[1][0] = 100
print(l)

# 2d array
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr[0])      # complete first row
print(arr[0][0])   # first element of first row
arr[1][0] = 100
print(arr)

[[1, 2, 3], [4, 5, 6]]
[1, 2, 3]
1
2
[[1, 2, 3], [100, 5, 6]]
[[1 2 3]
 [4 5 6]]
[1 2 3]
1
[[  1   2   3]
 [100   5   6]]


In [24]:
# list :
l = [1,2,3]
lm = l*2
print(lm)


# array:
import numpy as np
arr = np.array(l)
arrm = arr*2
print(arrm)

[1, 2, 3, 1, 2, 3]
[2 4 6]


In [28]:
# comparsion
# list
import time
start = time.time()
l = [i*2 for i in range(100000)]
print("list output:",time.time()-start)

# array
import numpy as np
start = time.time()
arr = np.arange(100000)*2
print("array output:",time.time()-start)

list output: 0.007731199264526367
array output: 0.002455472946166992


In [34]:
# zeros array :-
import numpy as np
arr = np.zeros(5)
print( "zeros array 1D",arr)
arr1 = np.zeros((5,2))
print("zeros array 2D","\n",arr1)


zeros array 1D [0. 0. 0. 0. 0.]
zeros array 2D 
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [35]:
# ones array :
import numpy as np
arr = np.ones(5)
print( "ones array 1D",arr)
arr1 = np.ones((5,2))
print("ones array 2D","\n",arr1)

ones array 1D [1. 1. 1. 1. 1.]
ones array 2D 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [40]:
import numpy as np
arr = np.zeros((3,4))
print(arr)
arrm = arr + 10
print("\n",arrm)


arr1 = np.ones((3,4))
print("\n",arr1)
arrm1 = arr1 * 10
print("\n",arrm1)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

 [[10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]]

 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

 [[10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]]


In [43]:
# full :-
import numpy as np
arr = np.full((3,4),10)         # define row and column and value
print(arr)

arr1 = np.full((4),11)
print("\n",arr1)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]

 [11 11 11 11]


In [48]:
# by zeros:
import numpy as np
arr1 = np.zeros((2,3))
print(arr1)
arr2 = arr1 + 6
print("\n",arr2)

# by full:
arr3 = np.full((2,3),1)
print("\n",arr3)

[[0. 0. 0.]
 [0. 0. 0.]]

 [[6. 6. 6.]
 [6. 6. 6.]]

 [[1 1 1]
 [1 1 1]]
