<a href="https://colab.research.google.com/github/anjali801/Data-science-45-internship/blob/main/day9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
# reshape:
import numpy as np
arr = np.arange(24)
up_arr = np.reshape(arr, (3 , 8))
print(up_arr)

arr1 = up_arr.flatten()             # flatter convert 1d & 2d array into 1d array
print(arr1)                          # create copy then work
print(up_arr)


[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]


In [12]:
# Example 3d :
arr = np.arange(24)
up_arr = np.reshape(arr, (2 , 3 , 4))
print(up_arr)
arr1 = up_arr.flatten()
print("\n",arr1)
print("\n",up_arr)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [14]:
# ravel :                            # ravel is like a flatter but there are some small defference  is flatter work on copy and ravel work on original means effect the original value
import numpy as np                    # work on original array
arr = np.arange(14).reshape(7,2)
print(arr)
arr1 = np.ravel(arr)
print("\n",arr1)
print("\n",arr)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]]

 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]

 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]]


In [10]:
# for 3d :
import numpy as np
arr = np.arange(24).reshape(2,3,4)
print(arr)
arr1 = np.ravel(arr)
print("\n",arr1)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [15]:
# transpose :
import numpy as np                                # in this method rows convert into columns
arr = np.arange(12).reshape(3,4)                   # columns convert int rows
print(arr)
arr1 = np.transpose(arr)
print("\n",arr1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [44]:
# slicing  :-

# 1D :
import numpy as np
arr = np.arange(11)
print(arr)
up_arr = arr[1:4]
print("\n",up_arr)

# 2D :
arr1 = np.arange(16).reshape(8,2)
print("\n",arr1)
up_arr1 = arr1[1:4,1:3]
print("\n",up_arr1)

# 3D :
arr2 = np.arange(24).reshape(2,3,4)
print("\n",arr2)
up_arr2 = arr2[1:2,1:3,1:3]
up1 = arr2[0:1,0:1,0:1]
print("\n",up_arr2)
print("\n",up1)




[ 0  1  2  3  4  5  6  7  8  9 10]

 [1 2 3]

 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]

 [[3]
 [5]
 [7]]

 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

 [[[17 18]
  [21 22]]]

 [[[0]]]


In [34]:
# while loop
# for loop

# for 1D , 2D , 3D  Array :
